spring:
  application:
    name: Scheduler-Job
#  batch:
#    jdbc:
#      initialize-schema: never  # JDBC 사용 안함
#    repository:
#      type: memory  # In-Memory JobRepository 사용 (DB 없이 실행)
#    job:
#      enabled: false  # 자동 실행 방지

management:
  otlp:  
    metrics:  
      export:  
        enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: ${port:8080}
  compression:
    enabled: true

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev
      
server:
  port: ${port:8080}
    
---

spring:
  config:
    activate:
      on-profile: prod
      
server:
  port: ${port:8080}
  
management:
  otlp:  
    metrics:  
      export: 
        enabled: true 
        url: https://otlp-gateway-prod-ap-northeast-0.grafana.net/otlp/v1/metrics
        headers:  
          Authorization: "Basic MTUzOTAzODpnbGNfZXlKdklqb2lNVFk0TURrNU1DSXNJbTRpT2lKelkyaGxaSFZzWlhJdGFtOWlMWE5qYUdWa2RXeGxjaTFxYjJJaUxDSnJJam9pT0RVd1ducHJTbFZpZVRSQ00yNHdlVFprY1dzNE9VRTNJaXdpYlNJNmV5SnlJam9pZFhNaWZYMD0="
        step: 10s
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  prometheus:
    metrics:
      export:
        enabled: true
