spring:
  application:
    name: Scheduler-Job
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: guney-consumer
      client-id: batch-server
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      
#  batch:
#    jdbc:
#      initialize-schema: never  # JDBC 사용 안함
#    repository:
#      type: memory  # In-Memory JobRepository 사용 (DB 없이 실행)
#    job:
#      enabled: false  # 자동 실행 방지

management:
  otlp:  
    metrics:  
      export:  
        enabled: false

server:
  port: ${port:8081}
  compression:
    enabled: true

jasypt:
  encryptor:
    password: 깔깔
    
풀어-보거라:
  훌랠릴: 끄얼끄얼
  랠룰: 낄낄

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev
      
server:
  port: ${port:8081}
    
---

spring:
  config:
    activate:
      on-profile: prod
      
server:
  port: ${port:80}
  
management:
  otlp:  
    metrics:  
      export: 
        enabled: true 
        url: https://otlp-gateway-prod-ap-northeast-0.grafana.net/otlp/v1/metrics
        headers:  
          Authorization: "Basic MTUzOTAzODpnbGNfZXlKdklqb2lNVFk0TURrNU1DSXNJbTRpT2lKelkyaGxaSFZzWlhJdGFtOWlMWE5qYUdWa2RXeGxjaTFxYjJJaUxDSnJJam9pT0RVd1ducHJTbFZpZVRSQ00yNHdlVFprY1dzNE9VRTNJaXdpYlNJNmV5SnlJam9pZFhNaWZYMD0="
        step: 10s
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, threaddump, threads
  prometheus:
    metrics:
      export:
        enabled: true

jasypt:
  encryptor:
    password: ${KKAL_KKAL}

풀어-보거라:
  훌랠릴: ENC(tNWzSG9f9HShTfSHxqTqS0amKWLZLAoimVJvIQwvMv3oT6qPuN/xUexCWzhg1rQ4)
  랠룰: ENC(m/WC78PJYkkrKbGYko0ADpVKFvOrsM9rrWiDrnLkOGeyQ7KNXwm7BWOMBFfRLNwB)