apiVersion: v1
kind: Service
metadata:
  name: scheduler-job-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: scheduler-job
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

